// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: voteRequestService.proto

package voteRequestService

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VoteRequestService_Vote_FullMethodName = "/voteRequestService.VoteRequestService/Vote"
)

// VoteRequestServiceClient is the client API for VoteRequestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VoteRequestServiceClient interface {
	Vote(ctx context.Context, in *VoteRequest, opts ...grpc.CallOption) (*VoteResponse, error)
}

type voteRequestServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVoteRequestServiceClient(cc grpc.ClientConnInterface) VoteRequestServiceClient {
	return &voteRequestServiceClient{cc}
}

func (c *voteRequestServiceClient) Vote(ctx context.Context, in *VoteRequest, opts ...grpc.CallOption) (*VoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VoteResponse)
	err := c.cc.Invoke(ctx, VoteRequestService_Vote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VoteRequestServiceServer is the server API for VoteRequestService service.
// All implementations must embed UnimplementedVoteRequestServiceServer
// for forward compatibility.
type VoteRequestServiceServer interface {
	Vote(context.Context, *VoteRequest) (*VoteResponse, error)
	mustEmbedUnimplementedVoteRequestServiceServer()
}

// UnimplementedVoteRequestServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVoteRequestServiceServer struct{}

func (UnimplementedVoteRequestServiceServer) Vote(context.Context, *VoteRequest) (*VoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Vote not implemented")
}
func (UnimplementedVoteRequestServiceServer) mustEmbedUnimplementedVoteRequestServiceServer() {}
func (UnimplementedVoteRequestServiceServer) testEmbeddedByValue()                            {}

// UnsafeVoteRequestServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VoteRequestServiceServer will
// result in compilation errors.
type UnsafeVoteRequestServiceServer interface {
	mustEmbedUnimplementedVoteRequestServiceServer()
}

func RegisterVoteRequestServiceServer(s grpc.ServiceRegistrar, srv VoteRequestServiceServer) {
	// If the following call pancis, it indicates UnimplementedVoteRequestServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VoteRequestService_ServiceDesc, srv)
}

func _VoteRequestService_Vote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoteRequestServiceServer).Vote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VoteRequestService_Vote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoteRequestServiceServer).Vote(ctx, req.(*VoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VoteRequestService_ServiceDesc is the grpc.ServiceDesc for VoteRequestService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VoteRequestService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "voteRequestService.VoteRequestService",
	HandlerType: (*VoteRequestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Vote",
			Handler:    _VoteRequestService_Vote_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "voteRequestService.proto",
}
